name: dopamin
description: A new Flutter project.

publish_to: "none"

version: 1.0.5+5

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_build_runner: ^0.0.7
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  crypto: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_line: ^3.2.2
  dropdown_button2: ^2.3.9
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  syncfusion_flutter_gauges: ^25.1.41
  vector_math: ^2.1.4
  
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_blurhash: ^0.8.2
  flutter_expandable_fab: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.9
  flutter_windowmanager: ^0.2.0
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  get_it: ^7.6.4
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  js: ^0.6.7
  loading_indicator: null
  lottie: ^2.7.0
  path: ^1.8.3
  permission_handler: ^11.0.1
  qr_code_scanner: ^1.0.1
  readmore: ^2.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  zoom_tap_animation: ^1.1.0
  device_info_plus: ^10.1.0
  percent_indicator: ^4.2.3
  animated_theme_switcher: ^2.0.8
  google_sign_in: ^6.2.1
 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/logox3.png"

dev_dependencies:
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/png/
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/font/Tajawal-Regular.ttf
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
