import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "courses": "الدورات",
          "institutions": "المؤسسات",
          "teachers": "المعلمين",
          "hello": "مرحبًا",
          "seeAll": "عرض الكل",
          "home": "الرئيسية",
          "myCourses": "دوراتي",
          "favorite": "المفضلة",
          "profile": "الملف الشخصي",
          "language": "اللغة",
          "notification": "الإشعارات",
          "english": "الإنجليزية",
          "arabic": "العربية",
          "edit": "تعديل",
          "pointOfSales": "نقاط البيع",
          "contactUs": "اتصل بنا",
          "about": "حول",
          "logout": "تسجيل الخروج",
          "settings": "الاعدادات",
          "buy": "شراء",
          "bought": "تم الشراء",
          "signIn": "تسجيل الدخول عن طريق الايميل",
          "signUp": "تسجيل حساب",
          "phone": "رقم الهاتف",
          "password": "كلمة السر",
          "dontHaveAnAccount": "ليس لديك حساب",
          "haveAnAccount": "لديك حساب",
          "fullName": "الاسم",
          "email": "البريد الألكتروني",
          "dateOfBirth": "تاريخ الولادة",
          "selectCity": "اختر المدينة",
          "agreeWith": "الموافقة على",
          "conditions": "الشروط",
          "?": " ؟ ",
          "teacher": "الاستاذ",
          "aboutCourse": "حول الدورة",
          "chapter": "الفصل",
          "lectures": "الدروس",
          "h": "ساعة",
          "sp": "ل.س",
          "payment": "الدفع",
          "chooseTypeOfPayment": "اختر نوع الدفع",
          "code": "الرمز",
          "quiz": "اختبار",
          "viewResult": "عرض النتيجة",
          "repeatQuiz": "اعادة الاختبار",
          "lecture": "الدرس",
          "downloadFiles": "تحميل الملفات",
          "topicsFavorite": "المواضيع المفضلة",
          "topics": "المواضيع",
          "notifications": "الاشعارات",
          "welcome": "هيا بنا لنبدأ الرحلة",
          "whoUs": "من نحن",
          "aboutDevelopers": "حول المطورين",
          "support": "الدعم الفني",
          "privacyPolicy": "سياسة الخصوصية",
          "let'sLearnSomeThingNewToday": "هيا لنتعلم شيْ جديد",
          "save": "حفظ",
          "editProfile": "تعديل معلومات الحساب",
          "city": "المدينة",
          "aboutLecture": "حول الدرس",
          "minute": "دقيقة",
          "result": "النتيجة",
          "failed": "خطأ",
          "success": "تمت العملية بنجاح",
          "warning": "تنبيه",
          "justNow": "الأن",
          "minutesAgo": "دقيقة",
          "hoursAgo": "ساعة",
          "yesterday": "أمس",
          "daysAgo": "يوم",
          "notFoundFiles": "لايوجد ملفات",
          "showMore": "عرض المزيد",
          "showLess": "عرض الاقل",
          "courseNotAvailableOnThisDevice":"هذه الدورة غير متاحة على هذا الجهاز",
                              "pleaseAnswerAllQuestions":"يرجى الاجابة على جميع الاسئلة"

        },
        "en": {
          "courses": "Courses",
          "institutions": "Institutions",
          "teachers": "Teachers",
          "hello": "Hello",
          "seeAll": "See All",
          "home": "Home",
          "myCourses": "My Courses",
          "favorite": "Favorite",
          "profile": "Profile",
          "language": "Language",
          "notification": "Notification",
          "english": "English",
          "arabic": "Arabic",
          "edit": "Edit",
          "pointOfSales": "Point of Sales",
          "contactUs": "Contact Us",
          "about": "About",
          "logout": "Logout",
          "settings": "Settings",
          "buy": "Buy",
          "bought": "Purchased",
          "signIn": "Sign in with google",
          "signUp": "Sign up",
          "phone": "Phone number",
          "password": "Password",
          "dontHaveAnAccount": "Don't have an account ?",
          "haveAnAccount": "Have account",
          "fullName": "Full name",
          "email": "Email",
          "dateOfBirth": "Date Of Birth",
          "selectCity": "Select city",
          "agreeWith": "Agree With",
          "conditions": "Conditions",
          "?": " ? ",
          "teacher": "Teacher",
          "aboutCourse": "About Course",
          "chapter": "Chapter",
          "lectures": "Lectures",
          "h": "H",
          "sp": "S.P",
          "payment": "Payment",
          "chooseTypeOfPayment": "Choose Type of Payment",
          "code": "Code",
          "quiz": "Quiz",
          "viewResult": "View Result",
          "repeatQuiz": "Repeat Quiz",
          "lecture": "Lecture",
          "downloadFiles": "download files",
          "topicsFavorite": "favorite topics",
          "topics": "topics",
          "notifications": "Notifications",
          "welcome": "Welcome",
          "whoUs": "Who us",
          "aboutDevelopers": "About developers",
          "support": "Support",
          "privacyPolicy": "Privacy policy",
          "let'sLearnSomeThingNewToday": "Let's learn something new today",
          "save": "Save",
          "editProfile": "Edit Profile",
          "city": "City",
          "aboutLecture": "About Lecture",
          "minute": "minute",
          "result": "Result",
          "failed": "Failed",
          "success": "Success",
          "warning": "Warning",
          "justNow": "just now",
          "minutesAgo": "minutes ago",
          "hoursAgo": "hours ago",
          "yesterday": "yesterday",
          "daysAgo": "days ago",
          "notFoundFiles": "Not found files",
            "showMore": "Show More",
          "showLess": "Show Less",
          "courseNotAvailableOnThisDevice":"This course not available on this device",
                    "pleaseAnswerAllQuestions":"please Answer All Questions"

        },
      };
}
